version: '3.7'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - './scripts/localstack:/docker-entrypoint-initaws.d'
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
